### PR TITLE
Helper to add includeHistory param

### PR DESCRIPTION
**Pull request by mingard**
- input Boolean (default=false)
- Roadmap to include filters when available

### CODE REVIEW

**Comment by mingard** [comment]
@eduardoboucas @jimlambie - fairly simple, but likely to change if history becomes filterable

**Comment by eduardoboucas** [comment]
Why the change to `withComposition`?

**Comment by eduardoboucas** [comment]
I'm happy to merge this. Thumbs up @jimlambie?

**Comment by jimlambie** [comment]
:white_check_mark:

**Pull request merged**
