### PR TITLE
Use callback feature of api-wrapper-core

### LINKED ISSUE #40: Add `inMedia` and `getSignedUrl` to terminators
The helpers for both `inMedia` and `getSignedUrl` exist in api-wrapper-core but need to be added here: https://github.com/dadi/api-wrapper/blob/master/lib/terminators.js#L14 

Currently some of the core functionality is missing, hence the label.

### PR DESCRIPTION
**Pull request by eduardoboucas**
This makes use of the new `callback` feature of `api-wrapper-core`, making `api-wrapper` a lot simpler. Instead of overloading each terminator method, it simply passes a callback to `api-wrapper-core`, which will be executed before each terminator returns.

It means that:

- New methods added to `api-wrapper-core` will automatically work in `api-wrapper` without any updates;
- `api-wrapper` becomes smaller in filesize and easier to maintain;
- The world becomes a better place.

It closes #40 and #36.

### CODE REVIEW

**Comment by jimlambie** [comment]
Do we need to port the same to 1.3.x or ensure the current version supports the way Publish is using it?

**Comment by eduardoboucas** [comment]
> Do we need to port the same to 1.3.x or ensure the current version supports the way Publish is using it?

@adamkdean has kindly agreed to test the previous version of Publish against this branch, since there's no obvious reason to keep two concurrent versions.

**Comment by adamkdean** [comment]
I'm a bit delayed on the testing but I will get round to it at some point later today!

**Comment by eduardoboucas** [comment]
I'll merge this, since we need this for latest version of Publish. Since the old version is pegged to 1.3.x it shouldn't make a difference anyway.

In any case, let me know when you get a chance to test it against this version @adamkdean, as I'm keen on having a single fork going forward.

Thanks!

**Comment by adamkdean** [comment]
@eduardoboucas yep will do. Sorry for the delay. Previous version of Publish uses 1.3.1 so once the new release is out I will test it and let you know.

**Comment by adamkdean** [comment]
@eduardoboucas have upgraded to `1.6.0` and my cursory checks don't reveal any issues. 👍 GJ

**Pull request merged**
